### ISSUE TITLE
Exception while trying to use create.js

### ISSUE THREAD

**Issue by merlin-zaraza** [Adventech/sabbath-school-lessons#1434]
```
node create.js -s '26/12/2020' -l 'uk' -q '2021-01' -t 'title' -d '' -h ''
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'case'
Require stack:
- /Users/vitalii/github/Adventech/sabbath-school-lessons/create.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/vitalii/github/Adventech/sabbath-school-lessons/create.js:26:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/vitalii/github/Adventech/sabbath-school-lessons/create.js'
  ]
}
```

```
node --version
v14.15.1
```

**Comment by merlin-zaraza** [comment]
Fixed by running `nmp install`. Please add this to README.md
