### ISSUE TITLE
Create new quarterly fails using create.js

### ISSUE THREAD

**Issue by toak** [Adventech/sabbath-school-lessons#1562]
This is the error I get when I use create.js to create a new quarter:

```
node create.js -s "26/06/2021" -l "de" -q "2021-03-cq" -c 13 -t "Test" -d "Description" -h "July · August · September 2021"
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/Users/tobi/Documents/GitHub/create.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Does anyone have a clue what I am doing wrong?

**Comment by toak** [comment]
This is my node version: Welcome to Node.js v14.16.1.
On a mac

**Comment by VitalikL** [comment]
@toak It looks like you are running this command from the wrong directory. Try navigating to `sabbath-school-lessons` and run it from there

**Comment by toak** [comment]
I did:

tobi@mba sabbath-school-lessons % pwd
/Users/tobi/Documents/GitHub/sabbath-school-lessons
tobi@mba % node create.js -s "26/06/2021" -l "de" -q "2021-03-cq" -c 13 -t "Test" -d "Description" -h "July · August · September 2021"

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'optimist'
Require stack:
- /Users/tobi/Documents/GitHub/sabbath-school-lessons/create.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/tobi/Documents/GitHub/sabbath-school-lessons/create.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/tobi/Documents/GitHub/sabbath-school-lessons/create.js' ]
}

**Comment by VitalikL** [comment]
@toak This is better now. You need to install few dependencies, just like this `npm install`.

**Comment by toak** [comment]
Works. Thanks for teaching me!
